# Generated by Django 4.0.5 on 2022-07-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='provider',
            field=models.ManyToManyField(blank=True, related_name='insurance', to='providers.provider'),
        ),
        migrations.AlterField(
            model_name='language',
            name='provider',
            field=models.ManyToManyField(blank=True, related_name='language', to='providers.provider'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='provider',
            field=models.ManyToManyField(blank=True, related_name='specialty', to='providers.provider'),
        ),
    ]
